### ISSUE TITLE
Append `?var=bws` to end of links ending in .aspx

### ISSUE THREAD

**Issue by tritterskamp** [drewconley/slicer#5]
I think the link builder bookmarklet tool currently does this.

**Comment by drewconley** [comment]
Interested in taking this on? I think this should be a really easy fix.
The table markup comes from `src/get-output.js` See the `getTableMarkupWithLink` function.
Could just check the `linkText` parameter and add `?var=bws` if it ends with .aspx. 

Also, realizing the name "linkText" is a little misleading because it seems like it would be the user facing words of a link. It could be changed to be "linkHref" or something like that. Maybe just "href'. Your call! No pressure to change it, just a thought.

**Comment by tritterskamp** [comment]
Sure! Should I fork your repo to work on this?

**Comment by drewconley** [comment]
Yeah, I was hoping to try out a Pull Request model for working on this
project.

**Comment by drewconley** [comment]
This has been merged!
